theme: jekyll-theme-minimal
title: Halle Bryant 
description: Welcome to my page! I am a data scientist, applied researcher and research communicator with a BA in Applied Mathematics from Brown University and MS in Data Science from SUNY - University at Buffalo. 
